language: python

dist: trusty

sudo: false

env:
  - PATH=/usr/lib/ccache:$PATH

cache:
  directories:
    - $HOME/.ccache

script:
  - export PATH=/usr/lib/ccache:$PATH
  - which gcc
  - which g++
  - echo 'before build'
  - ccache -s
  - echo 'int main() { int i = 1; }' > test.c
  - gcc test.c -o test.o -c
  - echo 'after build'
  - ccache -s
