language: python

dist: trusty

sudo: required

services: docker

python:
  - 2.7
  - 3.6

env:
  - NUMPY_VERSION=1.7.1
  - NUMPY_VERSION=1.12.1

cache: pip

install: docker build -t test-container --build-arg numpy_version=$NUMPY_VERSION .

script: docker run -v $PWD:$PWD test-container /bin/bash -c "cd $PWD && pytest"
