version: 2.0

jobs:
  "python3":
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - run: mkdir cached
      - run: echo $CIRCLE_SHA1 > cached/commit
      - restore_cache:
          keys:
            - v1-{{ .Branch }}-{{ checksum "cached/commit" }}
            - v1-{{ .Branch }}
            - v1-master
      - run: cat cached/checksum.txt
      - run: python --version
      - save_cache:
          paths:
            - jupyter-book/_build/.jupyter_cache
          key: v1-{{ .Branch }}-{{ checksum "cached/commit" }}

workflows:
  version: 2
  build:
    jobs:
      - "python3"
